### ISSUE TITLE
Making Google Map Embed Responsive

### ISSUE THREAD

**Issue by fixel99** [fixel99/tesla#13]
@russmaxdesign As per Pull #12 I'm not sure how to achieve this.

**Comment by fixel99** [comment]
Was able to make div responsive width wise (Will push the commit to google-maps branch #12 when I get home) but i'm not sure how to do the same height wise? Is there a way to lock the panels we created in css to the parent div so it never overflows?

**Comment by russmaxdesign** [comment]
There is a way to do this but easier to explain via skype. I will try to dig out an example I used when teaching - can be used for anything including maps and video.

**Comment by fixel99** [comment]
Sounds good. Can do any afternoon from tomorrow.

**Comment by fixel99** [comment]
@russmaxdesign Can you show me this tonight or within a couple days? Would really like to merge this. Thanks.

**Comment by russmaxdesign** [comment]
gah - sorry. Yes, I am back from dentist around 8:30pm so we can chat then?

**Comment by fixel99** [comment]
Sounds good

**Comment by fixel99** [comment]
Note: Fixed by changing height to min-height in .tesla-panel
