### ISSUE TITLE
Navbar not displaying properly on mobile

### ISSUE THREAD

**Issue by fixel99** [fixel99/tesla#17]
As seen in the gif,
![2017-05-08_22-14-11](https://cloud.githubusercontent.com/assets/11691966/25803917/aac75e12-343c-11e7-9249-8e5606e5efcf.gif)
 the navbar (Specifically "locations" overlapping and navspy combined with the navbar) does not display properly.

**Comment by fixel99** [comment]
Similarly the locations is cut off when the top navbar is used (As seen above)

**Comment by russmaxdesign** [comment]
so this can be closed?

**Comment by fixel99** [comment]
No it can't actually. I can't record my screen atm as the software I used to do so above is only available on windows and I only have my mac here at school. But this didn't actually fix the problem for me. Will record a gif when I get home if I don't figure something out before then.

**Comment by fixel99** [comment]
Seems to only be like 1 pixel off. Is there sometype of offset in the javascript file?

**Comment by fixel99** [comment]
fixed as of 196d488c141037b3fc8859f2be288b566e2395a4
