### ISSUE TITLE
Is there a special name for websites based on scrolling...

### ISSUE THREAD

**Issue by fixel99** [fixel99/tesla#20]
Rather than having multiple pages? Would like to know this to put it in my folio. Sorry I haven't contacted you about the website issues yet. Been really busy catching up on other work. @russmaxdesign

**Comment by russmaxdesign** [comment]
Probably "single page websites" or "long scrolling website" or a combination: "single page scrolling website"

**Comment by fixel99** [comment]
Cool thanks
