### ISSUE TITLE
Domains and Hosting

### ISSUE THREAD

**Issue by fixel99** [fixel99/tesla#26]
Hey @russmaxdesign 

(This turned into quite a long message. TLDR - can you help me setup my hosting if I struggle with it?)

While I haven't finished up on the scss or models page yet, I wanted to think and ask a few questions about hosting (If you know the answers to them).

So because i'm a student, I have access to the Github student pack which allows me to get a fairly discounted domain from namecheap as well as (basically) free cloud hosting from digital ocean. 

1) Firstly I'm not sure if I need anything else as i'm not really familiar with terms such as SSL, SSH and DNS. 

2) Secondly, i've attached an image of all the apps I could choose to install on the server easily. The alternative is to install them manually, which would be fun and interesting, however I don't really have the time to work it out. I know lamp includes Apache (which I don't really know anything about but know it has to do with normal websites?) but not sure if there is a better alternative. 

![oneclick apps](https://user-images.githubusercontent.com/11691966/28346368-00269106-6c74-11e7-92a8-a874a1428cdc.png)

3) Next it asks me to pick CPU/Storage (I will attach an image for this) I have 50$ free so do you reckon the 5$ tier would be good enough or should or go higher to make sure that it runs fast (as this project is purely to show off skills)

![screen shot 2017-07-19 at 2 30 20 pm](https://user-images.githubusercontent.com/11691966/28350822-e14489a8-6c8e-11e7-90d4-12607debe492.png)

4) After that is datacentre, while I know singapore would be closest, would it be better to go with a larger one such as US/UK?

![screen shot 2017-07-19 at 2 30 41 pm](https://user-images.githubusercontent.com/11691966/28350841-06c8db98-6c8f-11e7-9557-3d90c76a5eb5.png)

5) Next it lists additional options including: Private networking, Backups, IPv6, User Data and Monitoring. Are there certain options I should enable?

6) Finally adding SSH Keys. I have no idea what these are.

Thanks in advance.

**Comment by fixel99** [comment]
Got it working at: teslastudent.com

**Comment by russmaxdesign** [comment]
Hey Felix, apologies for the silence. A lot of these questions are not my area of expertise. Very sorry. However, I do know people who would probably be able to answer. Do you still need any assistance with this stuff?

**Comment by fixel99** [comment]
No I think i'm ok now thanks. Wasn't actually too hard to set up but it just seemed daunting when I arrived on that page :)

**Comment by russmaxdesign** [comment]
Great to hear!
