### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by fixel99** [fixel99/tesla#28]
Having major issues at school where the svgs on the sidebar are forbidden and not displaying however the rest of the website works? Not sure if there is any way I can fix this. Could it perhaps be due to the files being in a folder that doesn't have the right permissions set? @russmaxdesign 
![screen shot 2017-08-10 at 9 11 38 am](https://user-images.githubusercontent.com/11691966/29147737-46dc2ad6-7dac-11e7-9755-00399b153cb5.png)

**Comment by russmaxdesign** [comment]
@fixel99 That is a pain. I'm no expert in this area but some thoughts include:

1. Talk to IT team about adding SVG mime types to allow through firewall
2. Change all SVG to PNG.

The second option is easy but the images may not be as crisp as SVG versions. Happy to talk you through this second option if you want.

**Comment by fixel99** [comment]
Ok thanks for the ideas. I'm going to go talk to my teacher about it next period, but if nothing can be done, then i'll probably ask about the second option if I can't figure it out myself :)

**Comment by fixel99** [comment]
Ok @russmaxdesign i've converted all the images however they appear bigger than the svgs and I can't remember how we got the svgs to be small and centered?
![screen shot 2017-08-15 at 11 47 48 am](https://user-images.githubusercontent.com/11691966/29341877-8f4d972e-826a-11e7-83fe-60645e950b64.png)

**Comment by russmaxdesign** [comment]
@fixel99 The images need to be set with background-size. I can take a look some time tonight and get back to you. Do you have this fix on a specific branch / PR?

**Comment by fixel99** [comment]
@russmaxdesign No i'll push them when I get home as I can't from school, but i'll take a look on the background size

**Comment by fixel99** [comment]
Ok fixed. Thank you!

**Comment by russmaxdesign** [comment]
Woot!
