### ISSUE TITLE
Question: Do you want to add any scrolling magic?

### ISSUE THREAD

**Issue by russmaxdesign** [fixel99/tesla#3]
@fixel99 , Have you looked at any of the scrolling JavaScript libraries? These allow you to animate elements as the page scrolls down, so the text could slide in or fade up as the user scrolls. Lots of variations on these libraries to check out if interested... like these two (which look horrendous in their examples, but could be done more tastefully).

http://johnpolacek.github.io/superscrollorama/

http://mynameismatthieu.com/WOW/

**Comment by fixel99** [comment]
Both these websites are blocked at school, so will take a look at this when I get home
